### ISSUE TITLE
Token Import Error

### ISSUE THREAD

**Issue by zgrzezly** [RobertWojtowicz/export2garmin#48]
Still the same error I have trying to import token.
br

===============================================
Export 2 Garmin Connect v2.0 (import_tokens.py)
===============================================

27.11.2024-06:33:14 * Login e-mail: xxxx@gmail.com
27.11.2024-06:33:22 * Enter password:
27.11.2024-06:33:30 * MFA/2FA one-time code: 919605
Traceback (most recent call last):
  File "/home/pi/export2garmin-master/user/import_tokens.py", line 46, in <module>
    init_api()
  File "/home/pi/export2garmin-master/user/import_tokens.py", line 31, in init_api
    garmin.login()
  File "/usr/local/lib/python3.11/dist-packages/garminconnect/__init__.py", line 212, in login
    self.display_name = self.garth.profile["displayName"]
                        ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/garth/http.py", line 104, in profile
    assert isinstance(self._profile, dict)
AssertionError

**Comment by RobertWojtowicz** [comment]
Hi @zgrzezly 

Tempfix is ​​out: https://github.com/cyberjunky/python-garminconnect/releases/tag/0.2.22
Solve tproblem by executing this command (update module):
```sudo pip3 install --upgrade garminconnect --break-system-packages```
